### ISSUE TITLE
[Svelte 5]  `Tabs` causes `effect_update_depth_exceeded` error

### ISSUE THREAD

**Issue by jb-thery** [carbon-design-system/carbon-components-svelte#2366]
## Description

The `Tabs` component causes an infinite loop (`effect_update_depth_exceeded`) when used with Svelte 5, even without binding the `selected` prop.

This is the same issue that was fixed for the `Select` component in #2107 / PR #2108 (v0.87.7), but the fix was never applied to `Tabs`.

## Reproduction

**Environment:**
- carbon-components-svelte: 0.93.0
- svelte: 5.x
- sveltekit: 2.x

**Minimal reproduction:**

```svelte
<script>
  import { Modal, Tabs, Tab, TabContent } from 'carbon-components-svelte';

  let open = $state(false);
</script>

<button onclick={() => open = true}>Open Modal</button>

<Modal {open} on:close={() => open = false}>
  <Tabs>
    <Tab label="Tab 1" />
    <Tab label="Tab 2" />
    <svelte:fragment slot="content">
      <TabContent>Content 1</TabContent>
      <TabContent>Content 2</TabContent>
    </svelte:fragment>
  </Tabs>
</Modal>
```

**Error:**
```
Uncaught Svelte error: effect_update_depth_exceeded
Maximum update depth exceeded. This typically indicates that an effect reads and writes the same piece of state
```

## Root Cause

In `src/Tabs/Tabs.svelte`, there's a reactive loop between:

1. **Line 220** - Reactive statement:
   ```javascript
   $: currentIndex = selected;
   ```

2. **Line 207** - In `afterUpdate()`:
   ```javascript
   selected = currentIndex;
   ```

This creates a cycle:
1. `selected` changes → `$: currentIndex = selected` triggers
2. `currentIndex` changes → `afterUpdate()` runs
3. `afterUpdate()` sets `selected = currentIndex`
4. Go back to step 1

In Svelte 5, `$:` reactive statements are converted to effects, which makes this bidirectional update pattern cause infinite loops.

## Proposed Fix

Apply the same fix that was used for `Select` in PR #2108:

```diff
  afterUpdate(() => {
    // ... existing code ...

-   selected = currentIndex;
+   if (selected !== currentIndex) {
+     selected = currentIndex;
+   }

    if (prevIndex > -1 && prevIndex !== currentIndex) {
      dispatch("change", currentIndex);
    }

    prevIndex = currentIndex;
  });
```

This conditional check prevents unnecessary updates when the value hasn't actually changed, breaking the cycle.

## Workarounds

Until this is fixed, users can:

1. **Use `patch-package`** to apply the fix locally:
   ```bash
   yarn add -D patch-package postinstall-postinstall
   # Manually edit node_modules/carbon-components-svelte/src/Tabs/Tabs.svelte
   npx patch-package carbon-components-svelte
   ```

2. **Conditionally render Tabs** only when the parent container is visible:
   ```svelte
   <Modal {open}>
     {#if open}
       <Tabs>...</Tabs>
     {/if}
   </Modal>
   ```

3. **Create a custom Tabs component** that uses Svelte 5 patterns.

## Related Issues

- #2107 - `[Svelte 5] Select causes effect_update_depth_exceeded error when binding to same object` (Fixed in v0.87.7)
- PR #2108 - Fix for Select component

## Additional Context

This issue affects any usage of `Tabs` in a Svelte 5 application, particularly when:
- The component is mounted inside a Modal or other container
- The parent component uses `$state` for reactive variables
- Multiple reactive updates occur during initialization

The error can occur even at app initialization if Tabs is mounted (even when not visible), because Svelte 5's effect system tracks all reactive dependencies more strictly than Svelte 4.

**Comment by metonym** [comment]
Fixed in [v0.94.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.94.0)

**Comment by Sheepux** [comment]
Hi there ! Sorry to be the mood breaker but this didn't fix 😅

[Svelte playground](https://svelte.dev/playground/37dcec10caaf4254961a43e528d3da89?version=5.45.2#H4sIAAAAAAAACq1Qu3LCMBD8Fc3VxgK6OMaThCoFaUKXSyGbM3iQJY11kDAM_56RH0AY0kVqdLu629s9glE1QQKvLwsxV01ujXivVvSm9hBBWWnykHwcgQ8u_AoAREPPs3Ox35PmgOXK0z28sIbJsIcEUl80leMMjRBV7WzD4ogGOdylyn10VfTvpcrn3YAzubArpcOIkygbWwuEot17VNjaWRO0Rp360zh-mMZjhEc0qTyLo0k7PtmQWmWprsxWNKRnCJ4PmvyGiBHEpqFyhrBhdj6Rcmfcdh0XtpZ_6cnCe6m0jgvvEYTMUnkt1Cq32wvryISa0-A766yFt9AqbzeZIMgM-Q4z7RkeAhnclI1a12RYeG15hkPyCG3gl5NeQr1hRA9Pbhrkrw7k_5x2gW9sdPnIPqBUtsllaCACpm-GhJsdnT4jYFXpr8qsICmV9nT6AVGXh9LUAgAA)
Open console(f12) and change 0.92 to 0.94 and you'll get looping effect_update_depth_exceeded

**Comment by metonym** [comment]
@sheepux Thanks for reporting.

The regression was introduced in #2350 and affects v0.93.0 and v0.94.0.

Regression resolved via #2394:
- Fixed in [v0.94.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.94.1)
- Backported to [v0.93.1](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.93.1)

**Comment by Sheepux** [comment]
Thanks a lot for the reactivity. I can confirm that it's working fine with 0.94.1
