### ISSUE TITLE
MultiSelect intercepts keyboard events, interfering with browser

### ISSUE THREAD

**Issue by TheophileMot** [carbon-design-system/carbon-components-svelte#938]
When a MultiSelect has focus, it eats keyboard events. This makes it impossible to switch to a different tab (with Cmd+1, Cmd+2, etc.), or open Chrome dev tools (Cmd+Shift+C or F12), and so on.

Possibly related: clicking outside the MultiSelect (e.g., on a blank part of the page) has no effect. Compare this to a Search bar, for instance, where it is still possible to use keyboard shortcuts, and clicking away cancels the search.

Tested with Chrome on a Mac.

**Comment by metonym** [comment]
Fixed in [v0.50.5](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.50.5)

**Comment by TheophileMot** [comment]
@metonym I just upgraded to the latest version (v0.57.1) and noticed that this issue is still happening. (I tested on my own project as well as a fresh install of the SvelteKit template.)

**Comment by metonym** [comment]
Preemptively re-opening this so it doesn't get lost it notifications.

**Comment by metonym** [comment]
@TheophileMot Can you provide a repro?

Here's what I'm working with: https://svelte.dev/repl/e1c98a8ee79c49779610bfa359896224?version=3.46.4

**Comment by metonym** [comment]
Fixed in [v0.58.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.0)

**Comment by TheophileMot** [comment]
@metonym Sorry for the trouble, but this still appears to be an issue. Here is a [minimal REPL](https://svelte.dev/repl/84ec98a46a6f4e59a45e0dd707b9c610?version=3.46.4).

**Comment by metonym** [comment]
@TheophileMot Understood – thanks for following up.

So this is different from #848; keyboard events are intercepted when the menu is actually open.

**Comment by metonym** [comment]
@TheophileMot Can you give [v0.58.3](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.58.3) a try? Now, when the `MultiSelect` menu is open, the default keyboard behavior is prevented only for Space and ArrowUp/ArrowDown keys.

**Comment by TheophileMot** [comment]
@metonym Looks like it's working now. Thanks!
